image: Ubuntu

environment:
  BUILD_HOME: "/home/appveyor/projects/stm32-mini-lcd"
  TOOLCHAIN_HOME: "/home/appveyor/toolchain"

  TOOLCHAIN_URL: "https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2018q2/gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2"

init:

install:
  # Install Toolchain
  - mkdir "$TOOLCHAIN_HOME"
  - appveyor DownloadFile "$TOOLCHAIN_URL" -FileName "$TOOLCHAIN_HOME/gcc-arm-none-eabi.tar.bz2"
  - echo "Unpack Toolchain..."
  - tar -jxvf "$TOOLCHAIN_HOME/gcc-arm-none-eabi.tar.bz2" -C $TOOLCHAIN_HOME 1> /dev/null
  - export PATH="$PATH:$TOOLCHAIN_HOME/gcc-arm-none-eabi-7-2018-q2-update/bin"

build: off

build_script:
 - echo "Start build..."
 - cd $BUILD_HOME/Firmware/prototype/
 - make

artifacts:
 - path: build/*.elf build/*.hex build/*.bin
   name: Build
deploy:
- provider: GitHub
  auth_token:
    secure: UJvLV2sU0F+95nz3pnGyD1qmfln+rWu2PqcImHFbLdHi8N0BbiLyhVUO+t4BZTCl
  artifact: Build
  prerelease: true
